metadata_root: "./"
metadata_file_name: "calibration_metadata_all_heliostats.csv"
data_dir: "/base/path/data"
tower_file_name: "WRI1030197-tower-measurements.json"
scenarios_dir: "./examples/hyperparameter_optimization/scenarios"
results_dir: "./examples/hyperparameter_optimization/results"
plots_dir: "./examples/hyperparameter_optimization/plots"
propulate_logs_dir: "./examples/hyperparameter_optimization/logs"
minimum_number_of_measurements: 2
number_of_points_to_plot: 200
kinematics_reconstruction_image_type: "flux"
surface_reconstruction_image_type: "flux-centered"
excluded_heliostats_for_reconstruction: ["BE20", "AP14"]
parameter_ranges_kinematics:
  initial_learning_rate: [1e-7, 1e-2]
  scheduler: ["exponential", "reduce_on_plateau", "cyclic"]
  min_learning_rate: [1e-9, 1e-6]
  max_learning_rate: [1e-4, 1e-2]
  step_size_up: [100, 500]
  reduce_factor: [0.05, 0.5]
  patience: [3, 50]
  threshold: [1e-6, 1e-3]
  cooldown: [2, 20]
  gamma: [0.85, 0.999]
parameter_ranges_surface:
  number_of_surface_points: [30, 90]
  number_of_rays: [50, 120]
  number_of_control_points: [4, 12]
  nurbs_degree: [2, 3]
  initial_learning_rate: [1e-7, 1e-3]
  scheduler: ["exponential", "reduce_on_plateau", "cyclic"]
  min_learning_rate: [1e-9, 1e-7]
  max_learning_rate: [1e-4, 1e-2]
  sample_limit: [2, 6]
  step_size_up: [100, 500]
  reduce_factor: [0.05, 0.5]
  patience: [3, 50]
  threshold: [1e-6, 1e-3]
  cooldown: [2, 20]
  gamma: [0.85, 0.999]
  ideal_regularizer_weight: [0.0, 1.0]
  smoothness_regularizer_weight: [0.0, 1.0]
parameter_ranges_motor_positions:
  initial_learning_rate: [1e-7, 1e-3]
  scheduler: ["exponential", "reduce_on_plateau", "cyclic"]
  min_learning_rate: [1e-9, 1e-6]
  max_learning_rate: [1e-4, 1e-2]
  step_size_up: [100, 500]
  reduce_factor: [0.05, 0.5]
  patience: [3, 50]
  threshold: [1e-6, 1e-3]
  cooldown: [2, 20]
  gamma: [0.85, 0.999]
device: "cuda"
