metadata_root: "./"
metadata_file_name: "calibration_metadata_all_heliostats.csv"
data_dir: "/workVERLEIHNIX/share/PAINT"
tower_file_name: "WRI1030197-tower-measurements.json"
scenarios_dir: "./examples/paint_plots/scenarios"
results_dir: "./examples/paint_plots/results"
plots_dir: "./examples/paint_plots/plots"
minimum_number_of_measurements: 10
maximum_number_of_heliostats_for_reconstruction: 2200
excluded_heliostats_for_reconstruction: ["BE20", "AP14"]
calibration_image_type: "flux"
heliostats_for_raytracing:
  AA39: 149576
  AY26: 247613
  BC34: 82084
number_of_points_to_plot: 100
random_seed: 7
device: "cuda"
