metadata_root: "./examples/field_optimizations/"
metadata_file_name: "calibration_metadata_all_heliostats.csv"
data_dir: "/workVERLEIHNIX/share/PAINT"
tower_file_name: "WRI1030197-tower-measurements.json"
scenarios_dir: "./examples/field_optimizations/scenarios"
measured_data_dir: "./examples/field_optimizations/measured_data"
results_dir: "./examples/field_optimizations/results"
plots_dir: "./examples/field_optimizations/plots"
data_for_stral_dir: "./examples/field_optimizations/data_for_stral"
minimum_number_of_measurements: 2
kinematic_reconstruction_image_type: "flux"
surface_reconstruction_image_type: "flux-centered"
heliostats_for_plots:
  - "AK54"
  - "AM55"
  - "AM56"
random_seed: 7
device: "cuda"
surface_reconstruction_optimization_configuration:
  initial_learning_rate: 7e-5
  tolerance: 1e-15
  max_epoch: 3
  batch_size: 1
  log_step: 0
  early_stopping_delta: 5e-5
  early_stopping_patience: 200
  scheduler: "exponential"
  scheduler_parameters:
    gamma: 0.995
kinematic_reconstruction_optimization_configuration:
  initial_learning_rate: 8e-5
  tolerance: 0.0005
  max_epoch: 3
  batch_size: 50
  log_step: 0
  early_stopping_delta: 1e-4
  early_stopping_patience: 600
  scheduler: "reduce_on_plateau"
  scheduler_parameters:
    min: 1e-6
    reduce_factor: 0.0001
    patience: 50
    threshold: 1e-3
    cooldown: 10
aimpoint_optimization_configuration:
  initial_learning_rate: 8e-5
  tolerance: 0.0005
  max_epoch: 50
  batch_size: 946
  log_step: 0
  early_stopping_delta: 3e-4
  early_stopping_patience: 1000
  scheduler: "exponential"
  scheduler_parameters:
    gamma: 0.995
heliostat_list_baseline:
  - "AG48"
  - "AG49"
  - "AG50"
  - "AG51"
  - "AG52"
  - "AG53"
  - "AG54"
  - "AG55"
  - "AG56"
  - "AG57"
  - "AG58"
  - "AH48"
  - "AH49"
  - "AH50"
  - "AH55"
  - "AH56"
  - "AH57"
  - "AH58"
  - "AI48"
  - "AI49"
  - "AI50"
  - "AI51"
  - "AI52"
  - "AI53"
  - "AI54"
  - "AI55"
  - "AI56"
  - "AI57"
  - "AI58"
  - "AI59"
  - "AI60"
  - "AI61"
  - "AJ49"
  - "AJ50"
  - "AJ51"
  - "AJ53"
  - "AJ54"
  - "AJ55"
  - "AJ56"
  - "AJ57"
  - "AJ58"
  - "AJ61"
  - "AJ62"
  - "AK48"
  - "AK49"
  - "AK50"
  - "AK51"
  - "AK52"
  - "AK53"
  - "AK54"
  - "AK55"
  - "AK56"
  - "AK58"
  - "AK59"
  - "AK60"
  - "AK61"
  - "AK62"
  - "AL48"
  - "AL49"
  - "AL51"
  - "AL53"
  - "AL56"
  - "AL58"
  - "AL59"
  - "AL60"
  - "AL61"
  - "AL62"
  - "AM48"
  - "AM49"
  - "AM50"
  - "AM51"
  - "AM52"
  - "AM53"
  - "AM54"
  - "AM55"
  - "AM56"
  - "AM57"
  - "AM58"
  - "AM59"
  - "AM60"
  - "AM62"
  - "AN48"
  - "AN49"
  - "AN50"
  - "AN51"
  - "AN52"
  - "AN53"
  - "AN54"
  - "AN55"
  - "AN56"
  - "AN57"
  - "AN58"
  - "AN59"
  - "AN60"
  - "AN61"
  - "AN62"
